import mongoose from 'mongoose';
import Medicine from './models/Medicine.js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '.env') });

const medicines = [
  // --- SKIN CARE MEDICINES (10) ---
  {
    name: "Cetaphil Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "Skin Care Medicines",
    price: 450,
    originalPrice: 500,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=1",
    stock: 50,
    prescriptionRequired: false,
    composition: "Water, Cetyl Alcohol, Propylene Glycol",
    usage: "Apply to skin and massage gently. Rinse with water.",
    sideEffects: "Rare: minor irritation if allergic to ingredients.",
    description: "A mild, non-irritating formulation that soothes skin as it cleanses."
  },
  {
    name: "Hydrocortisone 1% Cream",
    brand: "Cortizone-10",
    category: "Skin Care Medicines",
    price: 320,
    originalPrice: 350,
    discount: 8,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=2",
    stock: 40,
    prescriptionRequired: false,
    composition: "Hydrocortisone 1%",
    usage: "Apply thin layer to affected area 2-3 times daily.",
    sideEffects: "Skin thinning with prolonged use, itching.",
    description: "Temporary relief of itching associated with minor skin irritations."
  },
  {
    name: "La Roche-Posay Effaclar Duo",
    brand: "La Roche-Posay",
    category: "Skin Care Medicines",
    price: 1200,
    originalPrice: 1350,
    discount: 11,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=3",
    stock: 25,
    prescriptionRequired: false,
    composition: "Salicylic Acid, Niacinamide",
    usage: "Apply to entire face morning and evening.",
    sideEffects: "Dryness, redness, peeling.",
    description: "Dual action acne treatment that reduces the number and severity of acne blemishes."
  },
  {
    name: "Mupirocin Ointment 2%",
    brand: "Bactroban",
    category: "Skin Care Medicines",
    price: 280,
    originalPrice: 300,
    discount: 7,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=4",
    stock: 35,
    prescriptionRequired: true,
    composition: "Mupirocin 2% w/w",
    usage: "Apply small amount to affected area 3 times daily for 10 days.",
    sideEffects: "Burning, stinging, pain, itching.",
    description: "Antibiotic ointment used to treat skin infections such as impetigo."
  },
  {
    name: "Neutrogena Hydro Boost Water Gel",
    brand: "Neutrogena",
    category: "Skin Care Medicines",
    price: 950,
    originalPrice: 1100,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=5",
    stock: 45,
    prescriptionRequired: false,
    composition: "Hyaluronic Acid, Glycerin",
    usage: "Apply evenly to face and neck after cleansing.",
    sideEffects: "Rare: skin rash or hives.",
    description: "A lightweight water gel that instantly quenches intensely dry skin."
  },
  {
    name: "Tretinoin 0.025% Cream",
    brand: "Retin-A",
    category: "Skin Care Medicines",
    price: 550,
    originalPrice: 600,
    discount: 8,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=6",
    stock: 30,
    prescriptionRequired: true,
    composition: "Tretinoin 0.025%",
    usage: "Apply a pea-sized amount to face once daily at bedtime.",
    sideEffects: "Skin peeling, redness, sensitivity to sunlight.",
    description: "Vitamin A derivative used to treat acne and reduce fine wrinkles."
  },
  {
    name: "Aveeno Daily Moisturizing Lotion",
    brand: "Aveeno",
    category: "Skin Care Medicines",
    price: 680,
    originalPrice: 750,
    discount: 9,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=7",
    stock: 55,
    prescriptionRequired: false,
    composition: "Oatmeal Prebiotic, Dimethicone",
    usage: "Apply as needed to dry skin.",
    sideEffects: "None reported.",
    description: "Nourishes dry skin with prebiotic oat and provides 24-hour hydration."
  },
  {
    name: "Bio-Oil Skincare Oil",
    brand: "Bio-Oil",
    category: "Skin Care Medicines",
    price: 490,
    originalPrice: 550,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=8",
    stock: 60,
    prescriptionRequired: false,
    composition: "PurCellin Oil, Vitamin A, Vitamin E",
    usage: "Apply twice daily for a minimum of 3 months.",
    sideEffects: "Skin irritation (rare).",
    description: "Specialist skincare oil that helps improve the appearance of scars and stretch marks."
  },
  {
    name: "Ketoconazole 2% Cream",
    brand: "Nizoral",
    category: "Skin Care Medicines",
    price: 180,
    originalPrice: 200,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=9",
    stock: 40,
    prescriptionRequired: false,
    composition: "Ketoconazole 2%",
    usage: "Apply to affected area 1-2 times daily.",
    sideEffects: "Itching, redness, irritation.",
    description: "Antifungal medication used to treat skin infections such as athlete's foot."
  },
  {
    name: "Eucerin Roughness Relief",
    brand: "Eucerin",
    category: "Skin Care Medicines",
    price: 1050,
    originalPrice: 1200,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,skin,cream,ointment,pill?lock=10",
    stock: 30,
    prescriptionRequired: false,
    composition: "Urea, Ceramide-3",
    usage: "Apply daily to body or as directed by physician.",
    sideEffects: "Stinging or burning (rare).",
    description: "Provides 48-hour hydration and smooths rough or bumpy skin."
  },

  // --- VITAMINS & SUPPLEMENTS (10) ---
  {
    name: "Vitamin C 500mg Tablets",
    brand: "Limcee",
    category: "Vitamins & Supplements",
    price: 45,
    originalPrice: 55,
    discount: 18,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=11",
    stock: 200,
    prescriptionRequired: false,
    composition: "Ascorbic Acid 500mg",
    usage: "Chew one tablet daily or as directed by physician.",
    sideEffects: "Stomach upset if taken in excess.",
    description: "Essential vitamin for immunity and antioxidant support."
  },
  {
    name: "Omega-3 Fish Oil 1000mg",
    brand: "HealthKart",
    category: "Vitamins & Supplements",
    price: 850,
    originalPrice: 1000,
    discount: 15,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=12",
    stock: 100,
    prescriptionRequired: false,
    composition: "Fish Oil, EPA, DHA",
    usage: "Take one capsule daily with food.",
    sideEffects: "Fishy aftertaste, nausea.",
    description: "Rich source of essential fatty acids for heart and brain health."
  },
  {
    name: "Multivitamin for Men",
    brand: "MuscleBlaze",
    category: "Vitamins & Supplements",
    price: 650,
    originalPrice: 750,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=13",
    stock: 80,
    prescriptionRequired: false,
    composition: "Vitamins A, C, D, E, B-Complex, Zinc",
    usage: "One tablet daily with breakfast.",
    sideEffects: "Nausea, bright yellow urine (normal).",
    description: "Comprehensive daily vitamin and mineral supplement tailored for men."
  },
  {
    name: "Biotin 5000mcg",
    brand: "Swisse",
    category: "Vitamins & Supplements",
    price: 980,
    originalPrice: 1100,
    discount: 11,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=14",
    stock: 60,
    prescriptionRequired: false,
    composition: "Biotin (Vitamin B7)",
    usage: "One capsule daily during or after a meal.",
    sideEffects: "Rare: skin rash, digestive upset.",
    description: "Supports healthy hair, skin, and nails, and aids in energy metabolism."
  },
  {
    name: "Zinc Gluconate 50mg",
    brand: "Nature's Bounty",
    category: "Vitamins & Supplements",
    price: 450,
    originalPrice: 500,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=15",
    stock: 120,
    prescriptionRequired: false,
    composition: "Zinc Gluconate 50mg",
    usage: "One tablet daily with a meal.",
    sideEffects: "Nausea, metallic taste.",
    description: "Essential mineral for immune system support and enzyme function."
  },
  {
    name: "Vitamin E 400IU",
    brand: "Evion",
    category: "Vitamins & Supplements",
    price: 120,
    originalPrice: 150,
    discount: 20,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=16",
    stock: 150,
    prescriptionRequired: false,
    composition: "dl-Alpha-Tocopheryl Acetate 400mg",
    usage: "One capsule daily or as directed by physician.",
    sideEffects: "Nausea, fatigue (rare).",
    description: "Antioxidant support for skin, hair, and immune health."
  },
  {
    name: "Calcium with Vitamin D3",
    brand: "Shelcal",
    category: "Vitamins & Supplements",
    price: 95,
    originalPrice: 110,
    discount: 14,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=17",
    stock: 180,
    prescriptionRequired: false,
    composition: "Calcium 500mg, Vitamin D3 250IU",
    usage: "One tablet daily or twice daily as prescribed.",
    sideEffects: "Constipation, bloating.",
    description: "Maintains strong bones and healthy teeth."
  },
  {
    name: "Probiotic for Gut Health",
    brand: "OptiBac",
    category: "Vitamins & Supplements",
    price: 1500,
    originalPrice: 1750,
    discount: 14,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=18",
    stock: 40,
    prescriptionRequired: false,
    composition: "Lactobacillus acidophilus, Bifidobacterium lactis",
    usage: "Take one capsule daily with breakfast.",
    sideEffects: "Gas, bloating (usually temporary).",
    description: "Premium probiotic blend to support digestive and immune health."
  },
  {
    name: "Ginseng Complex",
    brand: "Puritan's Pride",
    category: "Vitamins & Supplements",
    price: 1100,
    originalPrice: 1300,
    discount: 15,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=19",
    stock: 50,
    prescriptionRequired: false,
    composition: "Panax Ginseng, Royal Jelly",
    usage: "One capsule twice daily with meals.",
    sideEffects: "Insomnia, headache.",
    description: "Natural herbal supplement for energy, vitality, and focus."
  },
  {
    name: "Coenzyme Q10 100mg",
    brand: "Now Foods",
    category: "Vitamins & Supplements",
    price: 1850,
    originalPrice: 2100,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,vitamins,supplement,capsule,pill?lock=20",
    stock: 35,
    prescriptionRequired: false,
    composition: "Ubiquinone 100mg",
    usage: "One capsule 1 to 2 times daily with food.",
    sideEffects: "Upset stomach (rare).",
    description: "Antioxidant that supports cardiovascular health and cellular energy production."
  },

  // --- COLD & COUGH (10) ---
  {
    name: "Mucinex ER Tablets",
    brand: "Mucinex",
    category: "Cold & Cough",
    price: 750,
    originalPrice: 850,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=21",
    stock: 90,
    prescriptionRequired: false,
    composition: "Guaifenesin 600mg",
    usage: "Take 1 tablet every 12 hours with a full glass of water.",
    sideEffects: "Nausea, vomiting, stomach pain.",
    description: "Relieves chest congestion by thinning and loosening mucus."
  },
  {
    name: "Vicks VapoRub",
    brand: "Vicks",
    category: "Cold & Cough",
    price: 120,
    originalPrice: 150,
    discount: 20,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=22",
    stock: 150,
    prescriptionRequired: false,
    composition: "Camphor, Menthol, Eucalyptus Oil",
    usage: "Apply locally to chest and throat for cough relief.",
    sideEffects: "Skin irritation (rare).",
    description: "Topical ointment for relief of cough and minor muscular aches."
  },
  {
    name: "Alex Syrup Sugar Free",
    brand: "Glenmark",
    category: "Cold & Cough",
    price: 145,
    originalPrice: 160,
    discount: 9,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=23",
    stock: 120,
    prescriptionRequired: false,
    composition: "Dextromethorphan, Phenylephrine, Chlorpheniramine",
    usage: "10ml three times daily for adults.",
    sideEffects: "Drowsiness, dry mouth.",
    description: "Comprehensive relief from dry cough, cold, and nasal congestion."
  },
  {
    name: "Ascoril LS Syrup",
    brand: "Glenmark",
    category: "Cold & Cough",
    price: 115,
    originalPrice: 130,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=24",
    stock: 110,
    prescriptionRequired: true,
    composition: "Levosalbutamol, Ambroxol, Guaifenesin",
    usage: "5ml three times daily or as directed by physician.",
    sideEffects: "Tremors, increased heart rate, nausea.",
    description: "Relieves cough with mucus associated with asthma and bronchitis."
  },
  {
    name: "Otrivin Adult Nasal Spray",
    brand: "GSK",
    category: "Cold & Cough",
    price: 95,
    originalPrice: 110,
    discount: 14,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=25",
    stock: 200,
    prescriptionRequired: false,
    composition: "Xylometazoline Hydrochloride 0.1%",
    usage: "1 spray into each nostril up to 3 times daily.",
    sideEffects: "Dry nose, stinging sensation.",
    description: "Fast-acting relief from nasal congestion due to cold or sinusitis."
  },
  {
    name: "Strepsils Honey & Lemon",
    brand: "Reckitt",
    category: "Cold & Cough",
    price: 35,
    originalPrice: 40,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=26",
    stock: 300,
    prescriptionRequired: false,
    composition: "2,4-Dichlorobenzyl alcohol, Amylmetacresol",
    usage: "Dissolve one lozenge slowly in the mouth every 3 hours.",
    sideEffects: "Rare: sore tongue.",
    description: "Soothing relief for sore throat and mouth infections."
  },
  {
    name: "Honitus Herbal Syrup",
    brand: "Dabur",
    category: "Cold & Cough",
    price: 90,
    originalPrice: 100,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=27",
    stock: 140,
    prescriptionRequired: false,
    composition: "Tulsi, Mulethi, Banapsha, Kantkari",
    usage: "2 teaspoonfuls twice daily.",
    sideEffects: "None known.",
    description: "Effective ayurvedic remedy for all types of cough and sore throat."
  },
  {
    name: "Sinarest Tablets",
    brand: "Centaur",
    category: "Cold & Cough",
    price: 65,
    originalPrice: 75,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=28",
    stock: 250,
    prescriptionRequired: false,
    composition: "Chlorpheniramine, Paracetamol, Phenylephrine",
    usage: "One tablet every 6 hours for adults.",
    sideEffects: "Drowsiness, dry mouth, nausea.",
    description: "Multi-symptom relief from viral fever, cold, and nasal congestion."
  },
  {
    name: "Levocet M Tablets",
    brand: "Hetero",
    category: "Cold & Cough",
    price: 135,
    originalPrice: 155,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=29",
    stock: 180,
    prescriptionRequired: true,
    composition: "Levocetirizine 5mg, Montelukast 10mg",
    usage: "One tablet daily in the evening.",
    sideEffects: "Fatigue, dry mouth, sleepiness.",
    description: "Prevents allergy symptoms like sneezing and runny nose."
  },
  {
    name: "Grilinctus BM Syrup",
    brand: "Franco-Indian",
    category: "Cold & Cough",
    price: 105,
    originalPrice: 120,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,cough,syrup,flu,pill?lock=30",
    stock: 95,
    prescriptionRequired: true,
    composition: "Terbutaline Sulphate, Bromhexine Hydrochloride",
    usage: "10ml three times daily or as directed.",
    sideEffects: "Muscle tremors, palpitations, nausea.",
    description: "Relief from productive cough associated with bronchospasm."
  },

  // --- HEART & BP MEDICINES (10) ---
  {
    name: "Telmisartan 40mg (Telma)",
    brand: "Glenmark",
    category: "Heart & BP Medicines",
    price: 185,
    originalPrice: 210,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=31",
    stock: 150,
    prescriptionRequired: true,
    composition: "Telmisartan 40mg",
    usage: "Take as prescribed, usually once daily.",
    sideEffects: "Dizziness, fatigue, back pain.",
    description: "ARB for treatment of high blood pressure and prevention of heart attack/stroke."
  },
  {
    name: "Metoprolol Succinate 25mg",
    brand: "Metolar XT",
    category: "Heart & BP Medicines",
    price: 145,
    originalPrice: 165,
    discount: 12,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=32",
    stock: 120,
    prescriptionRequired: true,
    composition: "Metoprolol Succinate 25mg",
    usage: "Once daily or as prescribed by cardiologist.",
    sideEffects: "Dizziness, slow heart rate, fatigue.",
    description: "Beta-blocker for hypertension and chronic heart failure."
  },
  {
    name: "Ramipril 5mg (Cardace)",
    brand: "Sanofi",
    category: "Heart & BP Medicines",
    price: 180,
    originalPrice: 200,
    discount: 10,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=33",
    stock: 110,
    prescriptionRequired: true,
    composition: "Ramipril 5mg",
    usage: "Once daily, preferably at the same time.",
    sideEffects: "Dry cough, dizziness, high potassium levels.",
    description: "ACE inhibitor for blood pressure control and post-heart attack recovery."
  },
  {
    name: "Rosuvastatin 10mg (Rosuvas)",
    brand: "Sun Pharma",
    category: "Heart & BP Medicines",
    price: 240,
    originalPrice: 280,
    discount: 14,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=34",
    stock: 130,
    prescriptionRequired: true,
    composition: "Rosuvastatin 10mg",
    usage: "Once daily at bedtime.",
    sideEffects: "Muscle pain, weakness, liver enzyme changes.",
    description: "Highly effective statin for lowering LDL cholesterol and preventing heart disease."
  },
  {
    name: "Clopidogrel 75mg (Clopilet)",
    brand: "Sun Pharma",
    category: "Heart & BP Medicines",
    price: 165,
    originalPrice: 190,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=35",
    stock: 140,
    prescriptionRequired: true,
    composition: "Clopidogrel 75mg",
    usage: "Once daily with or without food.",
    sideEffects: "Bruising, bleeding, upset stomach.",
    description: "Antiplatelet medication to prevent blood clots in patients with heart disease."
  },
  {
    name: "Bisoprolol 2.5mg (Concor)",
    brand: "Merck",
    category: "Heart & BP Medicines",
    price: 130,
    originalPrice: 150,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=36",
    stock: 90,
    prescriptionRequired: true,
    composition: "Bisoprolol Fumarate 2.5mg",
    usage: "Once daily in the morning.",
    sideEffects: "Cold hands/feet, tiredness, slow heartbeat.",
    description: "Selective beta-blocker for hypertension and stable heart failure."
  },
  {
    name: "Valsartan 80mg (Diovan)",
    brand: "Novartis",
    category: "Heart & BP Medicines",
    price: 450,
    originalPrice: 520,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=37",
    stock: 75,
    prescriptionRequired: true,
    composition: "Valsartan 80mg",
    usage: "Once daily for blood pressure or twice for heart failure.",
    sideEffects: "Dizziness, low blood pressure, high potassium.",
    description: "ARB for blood pressure and heart failure management."
  },
  {
    name: "Nitroglycerin 2.6mg (Angispan)",
    brand: "USV",
    category: "Heart & BP Medicines",
    price: 210,
    originalPrice: 240,
    discount: 13,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=38",
    stock: 60,
    prescriptionRequired: true,
    composition: "Glyceryl Trinitrate 2.6mg Controlled Release",
    usage: "Twice daily as directed for prevention of angina.",
    sideEffects: "Headache, dizziness, flushing.",
    description: "Vasodilator for prevention of chest pain (angina) caused by heart disease."
  },
  {
    name: "Enalapril 5mg (Enam)",
    brand: "Dr. Reddy's",
    category: "Heart & BP Medicines",
    price: 85,
    originalPrice: 100,
    discount: 15,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=39",
    stock: 120,
    prescriptionRequired: true,
    composition: "Enalapril Maleate 5mg",
    usage: "Once daily or as prescribed.",
    sideEffects: "Dry cough, dizziness, low blood pressure.",
    description: "ACE inhibitor used to treat hypertension and congestive heart failure."
  },
  {
    name: "Chlorthalidone 12.5mg (CTD)",
    brand: "Ipca",
    category: "Heart & BP Medicines",
    price: 110,
    originalPrice: 130,
    discount: 15,
    image: "https://loremflickr.com/500/500/medical,heart,medical,pills,pill?lock=40",
    stock: 100,
    prescriptionRequired: true,
    composition: "Chlorthalidone 12.5mg",
    usage: "Once daily in the morning.",
    sideEffects: "Increased urination, low potassium, dizziness.",
    description: "Thiazide-like diuretic for hypertension and edema."
  },
  {
    "name": "Vitamin B-Complex with B12",
    "brand": "Becosules",
    "category": "Vitamins & Supplements",
    "price": 45,
    "originalPrice": 55,
    "discount": 18,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 150,
    "prescriptionRequired": false,
    "composition": "Vitamin B1, B2, B3, B6, B12, Calcium Pantothenate",
    "usage": "One capsule daily after meal.",
    "sideEffects": "Bright yellow urine (normal)",
    "description": "Essential B-vitamins for energy and nervous system health."
  },
  {
    "name": "Vitamin D3 2000IU Softgels",
    "brand": "Now Foods",
    "category": "Vitamins & Supplements",
    "price": 850,
    "originalPrice": 950,
    "discount": 11,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 120,
    "prescriptionRequired": false,
    "composition": "Vitamin D3 (Cholecalciferol) 2000IU",
    "usage": "One softgel daily with a fat-containing meal.",
    "sideEffects": "None at recommended dose.",
    "description": "Supports bone health and immune function."
  },
  {
    "name": "Magnesium Glycinate 400mg",
    "brand": "Solaray",
    "category": "Vitamins & Supplements",
    "price": 1200,
    "originalPrice": 1400,
    "discount": 14,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 80,
    "prescriptionRequired": false,
    "composition": "Magnesium Glycinate 400mg",
    "usage": "One to two capsules daily with food.",
    "sideEffects": "Loose stools (less common with glycinate form)",
    "description": "Highly absorbable magnesium for muscle and nerve relaxation."
  },
  {
    "name": "Zinc Picolinate 50mg",
    "brand": "Thorne",
    "category": "Vitamins & Supplements",
    "price": 1500,
    "originalPrice": 1700,
    "discount": 12,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 65,
    "prescriptionRequired": false,
    "composition": "Zinc Picolinate 50mg",
    "usage": "One capsule daily with a meal.",
    "sideEffects": "Nausea if taken on empty stomach.",
    "description": "Premium zinc supplement for immune support and skin health."
  },
  {
    "name": "Iron Bisglycinate 25mg",
    "brand": "Solgar",
    "category": "Vitamins & Supplements",
    "price": 950,
    "originalPrice": 1100,
    "discount": 14,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 90,
    "prescriptionRequired": false,
    "composition": "Iron (as Ferrous Bisglycinate) 25mg",
    "usage": "One vegetable capsule daily, preferably with a meal.",
    "sideEffects": "Constipation (minimal with bisglycinate form)",
    "description": "Gentle iron supplement that is non-constipating."
  },
  {
    "name": "Vitamin A 10000IU",
    "brand": "Nature Made",
    "category": "Vitamins & Supplements",
    "price": 450,
    "originalPrice": 550,
    "discount": 18,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 110,
    "prescriptionRequired": false,
    "composition": "Vitamin A (as Retinyl Palmitate)",
    "usage": "One softgel daily with a meal.",
    "sideEffects": "Dry skin, headache if overdosed.",
    "description": "Essential for eye health and immune function."
  },
  {
    "name": "Folic Acid 800mcg",
    "brand": "Jarrow Formulas",
    "category": "Vitamins & Supplements",
    "price": 320,
    "originalPrice": 400,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 130,
    "prescriptionRequired": false,
    "composition": "Folate (as Folic Acid)",
    "usage": "One capsule daily with food.",
    "sideEffects": "None reported.",
    "description": "Supports prenatal health and DNA synthesis."
  },
  {
    "name": "Potassium Citrate 99mg",
    "brand": "Life Extension",
    "category": "Vitamins & Supplements",
    "price": 680,
    "originalPrice": 800,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 100,
    "prescriptionRequired": false,
    "composition": "Potassium (from Potassium Citrate)",
    "usage": "One capsule one to five times daily.",
    "sideEffects": "Upset stomach if taken in excess.",
    "description": "Essential mineral for electrolyte balance and heart health."
  },
  {
    "name": "Selenium 200mcg",
    "brand": "Doctor's Best",
    "category": "Vitamins & Supplements",
    "price": 750,
    "originalPrice": 900,
    "discount": 17,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 85,
    "prescriptionRequired": false,
    "composition": "Selenium (from Yeast-Free L-Selenomethionine)",
    "usage": "One capsule daily with food.",
    "sideEffects": "Brittle nails, hair loss if overdosed.",
    "description": "Powerful antioxidant for thyroid and immune health."
  },
  {
    "name": "Biotin 10000mcg Maximum Strength",
    "brand": "Natrol",
    "category": "Vitamins & Supplements",
    "price": 1100,
    "originalPrice": 1300,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1550573104-e5746960d75b?w=500&h=500&fit=crop",
    "stock": 75,
    "prescriptionRequired": false,
    "composition": "Biotin 10mg",
    "usage": "One tablet daily with a meal.",
    "sideEffects": "Rare: skin breakouts.",
    "description": "Promotes healthy hair growth and strong nails."
  },
  {
    "name": "Salicylic Acid 2% Gel",
    "brand": "The Ordinary",
    "category": "Skin Care Medicines",
    "price": 550,
    "originalPrice": 650,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 60,
    "prescriptionRequired": false,
    "composition": "Salicylic Acid 2%",
    "usage": "Apply a small dot directly on spots.",
    "sideEffects": "Dryness, peeling.",
    "description": "Exfoliating solution to help fight blemishes."
  },
  {
    "name": "Niacinamide 10% + Zinc 1%",
    "brand": "The Ordinary",
    "category": "Skin Care Medicines",
    "price": 620,
    "originalPrice": 750,
    "discount": 17,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 70,
    "prescriptionRequired": false,
    "composition": "Niacinamide 10%, Zinc PCA 1%",
    "usage": "Apply to entire face morning and evening before heavier creams.",
    "sideEffects": "None reported.",
    "description": "Regulates sebum and minimizes pores."
  },
  {
    "name": "Benzoyl Peroxide 5% Gel",
    "brand": "Persa-Gel",
    "category": "Skin Care Medicines",
    "price": 450,
    "originalPrice": 500,
    "discount": 10,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 55,
    "prescriptionRequired": false,
    "composition": "Benzoyl Peroxide 5%",
    "usage": "Cleanse skin thoroughly before applying. Apply thin layer 1-3 times daily.",
    "sideEffects": "Skin irritation, dryness, bleaching of hair/fabrics.",
    "description": "Powerful acne treatment that kills bacteria."
  },
  {
    "name": "Adapalene Gel 0.1%",
    "brand": "Differin",
    "category": "Skin Care Medicines",
    "price": 1100,
    "originalPrice": 1300,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 40,
    "prescriptionRequired": false,
    "composition": "Adapalene 0.1%",
    "usage": "Apply a thin layer to clean, dry skin once daily at night.",
    "sideEffects": "Redness, scaling, burning (usually subsides after initial use).",
    "description": "Retinoid acne treatment for clear skin."
  },
  {
    "name": "Clindamycin Phosphate Gel 1%",
    "brand": "Cleocin T",
    "category": "Skin Care Medicines",
    "price": 380,
    "originalPrice": 450,
    "discount": 16,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 50,
    "prescriptionRequired": true,
    "composition": "Clindamycin 1%",
    "usage": "Apply a thin film to the affected area twice daily.",
    "sideEffects": "Burning, itching, dryness.",
    "description": "Antibiotic gel for inflammatory acne."
  },
  {
    "name": "Calamine Lotion",
    "brand": "Lacto Calamine",
    "category": "Skin Care Medicines",
    "price": 120,
    "originalPrice": 150,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 200,
    "prescriptionRequired": false,
    "composition": "Calamine, Zinc Oxide",
    "usage": "Shake well before use. Apply to affected area using cotton wool.",
    "sideEffects": "Rare: skin rash.",
    "description": "Relieves itching and soothing for skin irritations."
  },
  {
    "name": "Azelaic Acid 10% Suspension",
    "brand": "The Ordinary",
    "category": "Skin Care Medicines",
    "price": 780,
    "originalPrice": 900,
    "discount": 13,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 45,
    "prescriptionRequired": false,
    "composition": "Azelaic Acid 10%",
    "usage": "Apply to face AM and/or PM to improve visible brightness.",
    "sideEffects": "Stinging, itching (temporary).",
    "description": "Brightens skin tone and reduces redness."
  },
  {
    "name": "Urea 10% Cream",
    "brand": "Eucerin",
    "category": "Skin Care Medicines",
    "price": 950,
    "originalPrice": 1100,
    "discount": 14,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 55,
    "prescriptionRequired": false,
    "composition": "Urea 10%",
    "usage": "Apply once or twice daily to dry skin.",
    "sideEffects": "Transient burning or stinging.",
    "description": "Intense hydration for very dry and rough skin."
  },
  {
    "name": "Povidone-Iodine 5% Ointment",
    "brand": "Betadine",
    "category": "Skin Care Medicines",
    "price": 85,
    "originalPrice": 100,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 180,
    "prescriptionRequired": false,
    "composition": "Povidone-Iodine 5%",
    "usage": "Apply locally to affected area 1-3 times daily.",
    "sideEffects": "Rare: local skin irritation.",
    "description": "Antiseptic for minor cuts, scrapes and burns."
  },
  {
    "name": "Coal Tar 1% Shampoo",
    "brand": "Neutrogena T/Gel",
    "category": "Skin Care Medicines",
    "price": 1250,
    "originalPrice": 1500,
    "discount": 17,
    "image": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=500&h=500&fit=crop",
    "stock": 35,
    "prescriptionRequired": false,
    "composition": "Coal Tar Extract 1%",
    "usage": "Massage into wet hair, leave for several minutes, then rinse.",
    "sideEffects": "Staining, sensitivity to sunlight.",
    "description": "Treats dandruff, psoriasis and seborrheic dermatitis."
  },
  {
    "name": "Guaifenesin 400mg Tablets",
    "brand": "Robitussin",
    "category": "Cold & Cough",
    "price": 350,
    "originalPrice": 450,
    "discount": 22,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 100,
    "prescriptionRequired": false,
    "composition": "Guaifenesin 400mg",
    "usage": "Take 1 tablet every 4 hours. Do not exceed 6 tablets in 24 hours.",
    "sideEffects": "Nausea, vomiting.",
    "description": "Expectorant that helps loosen phlegm and thin bronchial secretions."
  },
  {
    "name": "Dextromethorphan HBr 30mg",
    "brand": "Delsym",
    "category": "Cold & Cough",
    "price": 850,
    "originalPrice": 1000,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 80,
    "prescriptionRequired": false,
    "composition": "Dextromethorphan Polistirex",
    "usage": "Take 10ml every 12 hours.",
    "sideEffects": "Drowsiness, dizziness.",
    "description": "12-hour cough suppressant for dry cough."
  },
  {
    "name": "Phenylephrine Nasal Drops",
    "brand": "Neo-Synephrine",
    "category": "Cold & Cough",
    "price": 180,
    "originalPrice": 220,
    "discount": 18,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 140,
    "prescriptionRequired": false,
    "composition": "Phenylephrine Hydrochloride 0.5%",
    "usage": "2 or 3 drops in each nostril every 4 hours.",
    "sideEffects": "Sneezing, stinging, rebound congestion.",
    "description": "Decongestant for relief of nasal stuffiness."
  },
  {
    "name": "Chlorpheniramine Maleate 4mg",
    "brand": "Piriton",
    "category": "Cold & Cough",
    "price": 45,
    "originalPrice": 60,
    "discount": 25,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 300,
    "prescriptionRequired": false,
    "composition": "Chlorpheniramine Maleate 4mg",
    "usage": "One tablet 4 to 6 hourly.",
    "sideEffects": "Drowsiness, blurred vision, dry mouth.",
    "description": "Effective antihistamine for allergy and cold symptoms."
  },
  {
    "name": "Loratadine 10mg",
    "brand": "Claritin",
    "category": "Cold & Cough",
    "price": 320,
    "originalPrice": 400,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 180,
    "prescriptionRequired": false,
    "composition": "Loratadine 10mg",
    "usage": "One tablet daily.",
    "sideEffects": "Headache, dry mouth.",
    "description": "Non-drowsy 24-hour allergy relief."
  },
  {
    "name": "Ambroxol Hydrochloride Syrup",
    "brand": "Mucosolvan",
    "category": "Cold & Cough",
    "price": 160,
    "originalPrice": 200,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 120,
    "prescriptionRequired": false,
    "composition": "Ambroxol 30mg/5ml",
    "usage": "10ml three times daily.",
    "sideEffects": "Mild gastrointestinal effects.",
    "description": "Secretolytic therapy for productive cough."
  },
  {
    "name": "Eucalyptus Oil 100% Pure",
    "brand": "Kama Ayurveda",
    "category": "Cold & Cough",
    "price": 550,
    "originalPrice": 650,
    "discount": 15,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 60,
    "prescriptionRequired": false,
    "composition": "Eucalyptus Globulus Leaf Oil",
    "usage": "Add a few drops to hot water for inhalation.",
    "sideEffects": "Skin irritation if used undiluted.",
    "description": "Natural relief for nasal and chest congestion."
  },
  {
    "name": "Benzonatate Capsules 100mg",
    "brand": "Tessalon Perles",
    "category": "Cold & Cough",
    "price": 680,
    "originalPrice": 850,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 50,
    "prescriptionRequired": true,
    "composition": "Benzonatate 100mg",
    "usage": "Take one capsule three times daily as needed for cough.",
    "sideEffects": "Numbness of tongue/throat if capsule is broken.",
    "description": "Non-narcotic cough medicine that numbs the throat."
  },
  {
    "name": "Saline Nasal Drops",
    "brand": "Nasivion S",
    "category": "Cold & Cough",
    "price": 65,
    "originalPrice": 75,
    "discount": 13,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 250,
    "prescriptionRequired": false,
    "composition": "Sodium Chloride 0.65%",
    "usage": "2-3 drops in each nostril as needed.",
    "sideEffects": "None.",
    "description": "Gentle saline solution for clearing nasal passages."
  },
  {
    "name": "DayQuil Cold & Flu",
    "brand": "Vicks",
    "category": "Cold & Cough",
    "price": 480,
    "originalPrice": 550,
    "discount": 13,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop",
    "stock": 150,
    "prescriptionRequired": false,
    "composition": "Acetaminophen, Dextromethorphan, Phenylephrine",
    "usage": "30ml every 4 hours. Do not exceed 4 doses.",
    "sideEffects": "Nausea, dizziness.",
    "description": "Multi-symptom non-drowsy relief for daytime."
  },
  {
    "name": "Lisinopril 10mg Tablets",
    "brand": "Zestril",
    "category": "Heart & BP Medicines",
    "price": 145,
    "originalPrice": 180,
    "discount": 19,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 100,
    "prescriptionRequired": true,
    "composition": "Lisinopril 10mg",
    "usage": "Take once daily or as directed by physician.",
    "sideEffects": "Dry cough, dizziness, fatigue.",
    "description": "ACE inhibitor for treatment of hypertension."
  },
  {
    "name": "Spironolactone 25mg",
    "brand": "Aldactone",
    "category": "Heart & BP Medicines",
    "price": 95,
    "originalPrice": 120,
    "discount": 21,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 120,
    "prescriptionRequired": true,
    "composition": "Spironolactone 25mg",
    "usage": "Take once or twice daily with food.",
    "sideEffects": "High potassium, headache, nausea.",
    "description": "Potassium-sparing diuretic for heart failure and hypertension."
  },
  {
    "name": "Warfarin 5mg Tablets",
    "brand": "Coumadin",
    "category": "Heart & BP Medicines",
    "price": 280,
    "originalPrice": 350,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 60,
    "prescriptionRequired": true,
    "composition": "Warfarin Sodium 5mg",
    "usage": "Take exactly as prescribed at the same time each day.",
    "sideEffects": "Bruising, bleeding risk.",
    "description": "Blood thinner used to prevent blood clots."
  },
  {
    "name": "Hydrochlorothiazide 25mg",
    "brand": "Microzide",
    "category": "Heart & BP Medicines",
    "price": 55,
    "originalPrice": 75,
    "discount": 27,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 200,
    "prescriptionRequired": true,
    "composition": "Hydrochlorothiazide 25mg",
    "usage": "Take once daily in the morning.",
    "sideEffects": "Frequent urination, dehydration, electrolyte imbalance.",
    "description": "Diuretic medication used to treat high blood pressure."
  },
  {
    "name": "Digoxin 0.25mg Tablets",
    "brand": "Lanoxin",
    "category": "Heart & BP Medicines",
    "price": 120,
    "originalPrice": 150,
    "discount": 20,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 80,
    "prescriptionRequired": true,
    "composition": "Digoxin 0.25mg",
    "usage": "Take once daily as directed by your cardiologist.",
    "sideEffects": "Nausea, blurred vision, dizziness.",
    "description": "Treats heart failure and certain types of irregular heartbeat."
  },
  {
    "name": "Irbesartan 150mg",
    "brand": "Avapro",
    "category": "Heart & BP Medicines",
    "price": 450,
    "originalPrice": 550,
    "discount": 18,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 70,
    "prescriptionRequired": true,
    "composition": "Irbesartan 150mg",
    "usage": "Take once daily with or without food.",
    "sideEffects": "Dizziness, low blood pressure.",
    "description": "ARB for treatment of high blood pressure."
  },
  {
    "name": "Hydralazine 25mg",
    "brand": "Apresoline",
    "category": "Heart & BP Medicines",
    "price": 185,
    "originalPrice": 220,
    "discount": 16,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 90,
    "prescriptionRequired": true,
    "composition": "Hydralazine Hydrochloride 25mg",
    "usage": "Take 2 to 4 times daily as directed.",
    "sideEffects": "Headache, palpitations, nausea.",
    "description": "Vasodilator used to treat high blood pressure."
  },
  {
    "name": "Furosemide 40mg (Lasix)",
    "brand": "Sanofi",
    "category": "Heart & BP Medicines",
    "price": 45,
    "originalPrice": 60,
    "discount": 25,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 150,
    "prescriptionRequired": true,
    "composition": "Furosemide 40mg",
    "usage": "Take once or twice daily as directed.",
    "sideEffects": "Increased urination, dehydration, low potassium.",
    "description": "Potent loop diuretic for edema and heart failure."
  },
  {
    "name": "Ezetimibe 10mg Tablets",
    "brand": "Zetia",
    "category": "Heart & BP Medicines",
    "price": 320,
    "originalPrice": 380,
    "discount": 16,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 100,
    "prescriptionRequired": true,
    "composition": "Ezetimibe 10mg",
    "usage": "Take once daily at any time.",
    "sideEffects": "Diarrhea, fatigue, joint pain.",
    "description": "Lowers cholesterol by reducing absorption in intestines."
  },
  {
    "name": "Prazosin 1mg (Minipress)",
    "brand": "Pfizer",
    "category": "Heart & BP Medicines",
    "price": 110,
    "originalPrice": 140,
    "discount": 21,
    "image": "https://images.unsplash.com/photo-1632833239869-c73228c25fb1?w=400&h=400&fit=crop",
    "stock": 85,
    "prescriptionRequired": true,
    "composition": "Prazosin 1mg",
    "usage": "Take two or three times daily as directed.",
    "sideEffects": "Dizziness on standing, headache, sleepiness.",
    "description": "Alpha-blocker used to treat high blood pressure."
  }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log("Connected to MongoDB...");

    // Optional: Clear existing medicines in these categories if you want a fresh start
    // const categoriesToClear = ['Skin Care Medicines', 'Vitamins & Supplements', 'Cold & Cough', 'Heart & BP Medicines'];
    // await Medicine.deleteMany({ category: { $in: categoriesToClear } });
    // console.log("Cleared existing medicines from targeted categories.");

    await Medicine.insertMany(medicines);
    console.log(`Successfully seeded ${medicines.length} medicines!`);
    
    process.exit(0);
  } catch (err) {
    console.error("Seeding failed:", err.message);
    process.exit(1);
  }
}

seed();
